# Generated by Django 4.0.1 on 2022-02-02 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unnamed_0', models.FloatField(blank=True, db_column='Unnamed: 0', null=True)),
                ('saldo_al', models.TextField(blank=True, db_column='Saldo al', null=True)),
                ('soc_field', models.TextField(blank=True, db_column='Soc.', null=True)),
                ('cta_mayor', models.BigIntegerField(blank=True, db_column='Cta.mayor', null=True)),
                ('material', models.BigIntegerField(blank=True, db_column='Material')),
                ('texto_breve_de_material', models.TextField(blank=True, db_column='Texto breve de material', null=True)),
                ('field_stock_total', models.TextField(blank=True, db_column='       Stock total', null=True)),
                ('umb', models.TextField(blank=True, db_column='UMB', null=True)),
                ('precio_variable', models.TextField(blank=True, db_column='Precio variable', null=True)),
                ('field_valor_total', models.TextField(blank=True, db_column='       Valor total', null=True)),
                ('catva', models.BigIntegerField(blank=True, db_column='CatVa', null=True)),
                ('prc', models.TextField(blank=True, db_column='Prc', null=True)),
                ('field_por', models.BigIntegerField(blank=True, db_column='   por', null=True)),
                ('mon_field', models.TextField(blank=True, db_column='Mon.', null=True)),
                ('tipval', models.TextField(blank=True, db_column='TipVal', null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='molino3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_de_planta', models.TextField(blank=True, db_column='AREA DE PLANTA', null=True)),
                ('ubicacion_funcional', models.TextField(blank=True, db_column='UBICACION FUNCIONAL', null=True)),
                ('descripcion_de_ubicacion_funcional', models.TextField(blank=True, db_column='DESCRIPCION DE UBICACION FUNCIONAL', null=True)),
                ('equipo', models.TextField(blank=True, db_column='EQUIPO', null=True)),
                ('equipo_hac', models.TextField(blank=True, db_column='EQUIPO_HAC', null=True)),
                ('descripcion_de_material', models.TextField(blank=True, db_column='DESCRIPCION DE MATERIAL', null=True)),
                ('cant_field', models.FloatField(blank=True, db_column='CANT.', null=True)),
                ('unidad_de_medida', models.TextField(blank=True, db_column='UNIDAD DE MEDIDA', null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuesto', to='ecommerce.inventario')),
            ],
            options={
                'db_table': 'molino3',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_de_planta', models.TextField(blank=True, db_column='AREA DE PLANTA', null=True)),
                ('ubicacion_funcional', models.TextField(blank=True, db_column='UBICACION FUNCIONAL', null=True)),
                ('descripcion_de_ubicacion_funcional', models.TextField(blank=True, db_column='DESCRIPCION DE UBICACION FUNCIONAL', null=True)),
                ('equipo', models.TextField(blank=True, db_column='EQUIPO', null=True)),
                ('equipo_hac', models.TextField(blank=True, db_column='EQUIPO_HAC', null=True)),
                ('descripcion_de_material', models.TextField(blank=True, db_column='DESCRIPCION DE MATERIAL', null=True)),
                ('cant_field', models.FloatField(blank=True, db_column='CANT.', null=True)),
                ('unidad_de_medida', models.TextField(blank=True, db_column='UNIDAD DE MEDIDA', null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuesto2', to='ecommerce.inventario')),
            ],
            options={
                'db_table': 'equipos',
                'managed': True,
            },
        ),
    ]
