# Generated by Django 4.2 on 2023-04-26 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCostos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='encabezado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.centrodecostos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Ingenieros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Responsables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='reportehoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('horainicio', models.TimeField()),
                ('horafinal', models.TimeField()),
                ('descripcion', models.CharField(max_length=400)),
                ('finalizacion', models.CharField(max_length=200)),
                ('encabezado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='components.encabezado')),
            ],
        ),
        migrations.AddField(
            model_name='encabezado',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.responsables'),
        ),
        migrations.AddField(
            model_name='encabezado',
            name='ingeniero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.ingenieros'),
        ),
        migrations.AddField(
            model_name='centrodecostos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.empresa'),
        ),
    ]
