# Generated by Django 4.1 on 2023-04-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_alter_centrodecostos_id_alter_empresa_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredientes',
        ),
        migrations.DeleteModel(
            name='operaciones',
        ),
        migrations.RemoveField(
            model_name='productionorders1_sap',
            name='itemcode',
        ),
        migrations.RemoveField(
            model_name='productionorders2_sap',
            name='itemcode',
        ),
        migrations.RemoveField(
            model_name='productionorders2_sap',
            name='parentkey',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='id_semielaborado',
        ),
        migrations.RemoveField(
            model_name='recetassap',
            name='id_ingrediente',
        ),
        migrations.RemoveField(
            model_name='recetassap',
            name='id_semielaborado',
        ),
        migrations.DeleteModel(
            name='RecipesSAP',
        ),
        migrations.RemoveField(
            model_name='reportebatch',
            name='id_ingrediente',
        ),
        migrations.RemoveField(
            model_name='reportebatch',
            name='id_semielaborado',
        ),
        migrations.RemoveField(
            model_name='reportesap',
            name='id_semielaborado',
        ),
        migrations.DeleteModel(
            name='Semielaborados',
        ),
        migrations.DeleteModel(
            name='MaestroDeMateriales',
        ),
        migrations.DeleteModel(
            name='ProductionOrders1_SAP',
        ),
        migrations.DeleteModel(
            name='ProductionOrders2_SAP',
        ),
        migrations.DeleteModel(
            name='Recetas',
        ),
        migrations.DeleteModel(
            name='RecetasSAP',
        ),
        migrations.DeleteModel(
            name='ReporteBatch',
        ),
        migrations.DeleteModel(
            name='ReporteSAP',
        ),
    ]
