# Generated by Django 4.1 on 2023-08-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_producciondiaria_ho1_producciondiaria_ho10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producciondiaria',
            name='fecha',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='fecha'),
        ),
    ]
