# Generated by Django 2.1.15 on 2023-03-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteLAB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cemento', models.CharField(blank=True, max_length=60, null=True, verbose_name='Cemento')),
                ('ProductoId', models.PositiveIntegerField(blank=True, null=True, verbose_name='ProductoId')),
                ('CargarPromedioId', models.PositiveIntegerField(blank=True, null=True, verbose_name='CargarPromedioId')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='C_Fecha')),
                ('month', models.CharField(blank=True, max_length=15, null=True, verbose_name='D_Mes')),
                ('week', models.PositiveIntegerField(blank=True, null=True, verbose_name='E_Semana')),
                ('Molino', models.CharField(blank=True, max_length=15, null=True, verbose_name='G_Molino')),
                ('Silo', models.CharField(blank=True, max_length=15, null=True, verbose_name='H_Destino')),
                ('FAnalista', models.CharField(blank=True, max_length=30, null=True, verbose_name='V_FAnalista')),
                ('QAnalista', models.CharField(blank=True, max_length=30, null=True, verbose_name='BL_QAnalista')),
                ('Comentarios', models.CharField(blank=True, max_length=60, null=True, verbose_name='CC_Comentarios')),
            ],
            options={
                'verbose_name': 'ReporteLAB',
                'verbose_name_plural': 'ReportesLAB',
            },
        ),
    ]
