# Generated by Django 5.0.1 on 2024-05-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteLAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=4, null=True, verbose_name='Tipo')),
                ('cemento', models.CharField(blank=True, max_length=60, null=True, verbose_name='Cemento')),
                ('productoid', models.PositiveIntegerField(blank=True, null=True, verbose_name='ProductoId')),
                ('cargarpromedioid', models.PositiveIntegerField(blank=True, null=True, verbose_name='CargarPromedioId')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='C_Fecha')),
                ('month', models.CharField(blank=True, max_length=15, null=True, verbose_name='D_Mes')),
                ('week', models.PositiveIntegerField(blank=True, null=True, verbose_name='E_Semana')),
                ('proc_clinker', models.CharField(blank=True, max_length=60, null=True, verbose_name='F_Proc_Clinker')),
                ('molino', models.CharField(blank=True, max_length=15, null=True, verbose_name='G_Molino')),
                ('silo', models.CharField(blank=True, max_length=15, null=True, verbose_name='H_Destino')),
                ('fanalista', models.CharField(blank=True, max_length=30, null=True, verbose_name='V_FAnalista')),
                ('qanalista', models.CharField(blank=True, max_length=30, null=True, verbose_name='BL_QAnalista')),
                ('comentarios', models.CharField(blank=True, max_length=240, null=True, verbose_name='CC_Comentarios')),
                ('blaine_cm2g', models.IntegerField(blank=True, null=True, verbose_name='K_Blaine(cm2/g)')),
                ('retenido325', models.FloatField(blank=True, null=True, verbose_name='L_Retenido325(%)')),
                ('_330μm', models.FloatField(blank=True, null=True, verbose_name='M_3_30µm(%)')),
                ('autoclave', models.FloatField(blank=True, null=True, verbose_name='N_Autoclave(%)')),
                ('barras14dias', models.FloatField(blank=True, null=True, verbose_name='O_Barras14días(%)')),
                ('contenidoaire', models.FloatField(blank=True, null=True, verbose_name='P_ContenidoAire(%)')),
                ('retencionagua', models.FloatField(blank=True, null=True, verbose_name='Q_RetenciónAgua(%)')),
                ('falsofraguado', models.FloatField(blank=True, null=True, verbose_name='R_FalsoFraguado(%)')),
                ('consistencianormal', models.FloatField(blank=True, null=True, verbose_name='S_ConsistenciaNormal(%)')),
                ('fraguadoi', models.IntegerField(blank=True, null=True, verbose_name='T_FraguadoInicial')),
                ('fraguadof', models.IntegerField(blank=True, null=True, verbose_name='U_FraguaFinal')),
                ('aguacemento', models.FloatField(blank=True, null=True, verbose_name='W_AguaCemento(%)')),
                ('flujo', models.FloatField(blank=True, null=True, verbose_name='X_Flujo')),
                ('r1cubo1', models.FloatField(blank=True, null=True, verbose_name='Y_R1Diacubo1')),
                ('r1cubo2', models.FloatField(blank=True, null=True, verbose_name='Z_R1Diacubo2')),
                ('r1cubo3', models.FloatField(blank=True, null=True, verbose_name='AA_R1Diacubo3')),
                ('r1', models.FloatField(blank=True, null=True, verbose_name='AB_R1Dia')),
                ('r3cubo1', models.FloatField(blank=True, null=True, verbose_name='AC_R3Diacubo1')),
                ('r3cubo2', models.FloatField(blank=True, null=True, verbose_name='AD_R3Diacubo2')),
                ('r3cubo3', models.FloatField(blank=True, null=True, verbose_name='AE_R3Diacubo3')),
                ('r3', models.FloatField(blank=True, null=True, verbose_name='AF_R3Dia')),
                ('r7cubo1', models.FloatField(blank=True, null=True, verbose_name='AG_R7Diacubo1')),
                ('r7cubo2', models.FloatField(blank=True, null=True, verbose_name='AH_R7Diacubo2')),
                ('r7cubo3', models.FloatField(blank=True, null=True, verbose_name='AI_R7Diacubo3')),
                ('r7', models.FloatField(blank=True, null=True, verbose_name='AJ_R7Dia')),
                ('r28cubo1', models.FloatField(blank=True, null=True, verbose_name='AK_R28Diacubo1')),
                ('r28cubo2', models.FloatField(blank=True, null=True, verbose_name='AL_R28Diacubo2')),
                ('r28cubo3', models.FloatField(blank=True, null=True, verbose_name='AM_R28Diacubo3')),
                ('r28', models.FloatField(blank=True, null=True, verbose_name='AN_R28Dia')),
                ('densidad', models.FloatField(blank=True, null=True, verbose_name='AS_Densidad_p(g/cm3)')),
                ('sio2', models.FloatField(blank=True, null=True, verbose_name='AT_%SiO2')),
                ('ai2o3', models.FloatField(blank=True, null=True, verbose_name='AU_%AI2O3')),
                ('fe2o3', models.FloatField(blank=True, null=True, verbose_name='AV_Fe2O3%')),
                ('cao', models.FloatField(blank=True, null=True, verbose_name='AW_%CaO')),
                ('mgo', models.FloatField(blank=True, null=True, verbose_name='AX_%MgO')),
                ('so3', models.FloatField(blank=True, null=True, verbose_name='AY_%SO3')),
                ('na2o', models.FloatField(blank=True, null=True, verbose_name='AZ_%Na2O')),
                ('k2o', models.FloatField(blank=True, null=True, verbose_name='BA_%K2O')),
                ('tio2', models.FloatField(blank=True, null=True, verbose_name='BB_%TiO2')),
                ('p2o5', models.FloatField(blank=True, null=True, verbose_name='BC_%P2O5')),
                ('pi', models.FloatField(blank=True, null=True, verbose_name='BD_%PI')),
                ('callibre', models.FloatField(blank=True, null=True, verbose_name='BE_%Callibre')),
                ('ri', models.FloatField(blank=True, null=True, verbose_name='BG_%RI')),
                ('c3s', models.FloatField(blank=True, null=True, verbose_name='BH_%C3S')),
                ('c2s', models.FloatField(blank=True, null=True, verbose_name='BI_%C2S')),
                ('c3a', models.FloatField(blank=True, null=True, verbose_name='BJ_%C3A')),
                ('c4af', models.FloatField(blank=True, null=True, verbose_name='BK_%C4AF')),
                ('toneladas', models.FloatField(blank=True, null=True, verbose_name='BM_Toneladas')),
            ],
            options={
                'verbose_name': 'ReporteLAB',
                'verbose_name_plural': 'ReportesLAB',
            },
        ),
    ]
