# Generated by Django 2.1.15 on 2023-03-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_auto_20230331_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportelab',
            name='proc_clinker',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='F_Proc_Clinker'),
        ),
    ]
