# Generated by Django 2.1.15 on 2023-03-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_auto_20230331_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelab',
            name='_330μm',
            field=models.FloatField(blank=True, null=True, verbose_name='M_3_30µm(%)'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='blaine_cm2g',
            field=models.IntegerField(blank=True, null=True, verbose_name='K_Blaine(cm2/g)'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='retenido325',
            field=models.FloatField(blank=True, null=True, verbose_name='L_Retenido325(%)'),
        ),
    ]
