# Generated by Django 2.1.15 on 2023-03-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_auto_20230331_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelab',
            name='autoclave',
            field=models.FloatField(blank=True, null=True, verbose_name='N_Autoclave(%)'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='barras14dias',
            field=models.FloatField(blank=True, null=True, verbose_name='O_Barras14días(%)'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='contenidoaire',
            field=models.FloatField(blank=True, null=True, verbose_name='P_ContenidoAire(%)'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='falsofraguado',
            field=models.FloatField(blank=True, null=True, verbose_name='R_FalsoFraguado(%)'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='retencionagua',
            field=models.FloatField(blank=True, null=True, verbose_name='Q_RetenciónAgua(%)'),
        ),
    ]
