# Generated by Django 2.1.15 on 2023-03-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_auto_20230331_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelab',
            name='consistencianormal',
            field=models.FloatField(blank=True, null=True, verbose_name='S_ConsistenciaNormal(%)'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='fraguadofinal',
            field=models.FloatField(blank=True, null=True, verbose_name='U_FraguadoFinal'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='fraguadoinicial',
            field=models.FloatField(blank=True, null=True, verbose_name='T_FraguadoInicial'),
        ),
    ]
