# Generated by Django 2.1.15 on 2023-03-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0008_auto_20230331_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportelab',
            name='fraguadofinal',
            field=models.IntegerField(blank=True, null=True, verbose_name='U_FraguadoFinal'),
        ),
        migrations.AlterField(
            model_name='reportelab',
            name='fraguadoinicial',
            field=models.IntegerField(blank=True, null=True, verbose_name='T_FraguadoInicial'),
        ),
    ]
