# Generated by Django 2.1.15 on 2023-03-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0009_auto_20230331_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportelab',
            name='fraguadofinal',
        ),
        migrations.RemoveField(
            model_name='reportelab',
            name='fraguadoinicial',
        ),
        migrations.AddField(
            model_name='reportelab',
            name='fraguadof',
            field=models.IntegerField(blank=True, null=True, verbose_name='U_FraguaFin'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='fraguadoi',
            field=models.IntegerField(blank=True, null=True, verbose_name='T_FraguaInicio'),
        ),
    ]
