# Generated by Django 2.1.15 on 2023-04-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0010_auto_20230331_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelab',
            name='aguacemento',
            field=models.FloatField(blank=True, null=True, verbose_name='W_Agua_Cemento(%)'),
        ),
        migrations.AlterField(
            model_name='reportelab',
            name='fraguadof',
            field=models.IntegerField(blank=True, null=True, verbose_name='U_FraguaFinal'),
        ),
        migrations.AlterField(
            model_name='reportelab',
            name='fraguadoi',
            field=models.IntegerField(blank=True, null=True, verbose_name='T_FraguadoInicial'),
        ),
    ]
