# Generated by Django 2.1.15 on 2023-04-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0011_auto_20230403_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelab',
            name='flujo',
            field=models.IntegerField(blank=True, null=True, verbose_name='X_Flujo'),
        ),
    ]
