# Generated by Django 2.1.15 on 2023-04-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0012_reportelab_flujo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelab',
            name='r1',
            field=models.FloatField(blank=True, null=True, verbose_name='AB_R1Dia'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='r1cubo1',
            field=models.FloatField(blank=True, null=True, verbose_name='Y_R1Diacubo1'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='r1cubo2',
            field=models.FloatField(blank=True, null=True, verbose_name='Z_R1Diacubo2'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='r1cubo3',
            field=models.FloatField(blank=True, null=True, verbose_name='AA_R1Diacubo3'),
        ),
        migrations.AlterField(
            model_name='reportelab',
            name='aguacemento',
            field=models.FloatField(blank=True, null=True, verbose_name='W_AguaCemento(%)'),
        ),
        migrations.AlterField(
            model_name='reportelab',
            name='flujo',
            field=models.FloatField(blank=True, null=True, verbose_name='X_Flujo'),
        ),
    ]
