# Generated by Django 2.1.15 on 2023-04-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0013_auto_20230403_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelab',
            name='r3',
            field=models.FloatField(blank=True, null=True, verbose_name='AF_R3Dia'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='r3cubo1',
            field=models.FloatField(blank=True, null=True, verbose_name='AC_R3Diacubo1'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='r3cubo2',
            field=models.FloatField(blank=True, null=True, verbose_name='AD_R3Diacubo2'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='r3cubo3',
            field=models.FloatField(blank=True, null=True, verbose_name='AE_R3Diacubo3'),
        ),
    ]
