# Generated by Django 2.1.15 on 2023-04-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0014_auto_20230410_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelab',
            name='r7',
            field=models.FloatField(blank=True, null=True, verbose_name='AF_R7Dia'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='r7cubo1',
            field=models.FloatField(blank=True, null=True, verbose_name='AC_R7Diacubo1'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='r7cubo2',
            field=models.FloatField(blank=True, null=True, verbose_name='AD_R7Diacubo2'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='r7cubo3',
            field=models.FloatField(blank=True, null=True, verbose_name='AE_R7Diacubo3'),
        ),
    ]
