# Generated by Django 2.1.15 on 2023-04-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0015_auto_20230410_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelab',
            name='r28',
            field=models.FloatField(blank=True, null=True, verbose_name='AN_R28Dia'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='r28cubo1',
            field=models.FloatField(blank=True, null=True, verbose_name='AK_R28Diacubo1'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='r28cubo2',
            field=models.FloatField(blank=True, null=True, verbose_name='AL_R28Diacubo2'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='r28cubo3',
            field=models.FloatField(blank=True, null=True, verbose_name='AM_R28Diacubo3'),
        ),
        migrations.AlterField(
            model_name='reportelab',
            name='r7',
            field=models.FloatField(blank=True, null=True, verbose_name='AJ_R7Dia'),
        ),
        migrations.AlterField(
            model_name='reportelab',
            name='r7cubo1',
            field=models.FloatField(blank=True, null=True, verbose_name='AG_R7Diacubo1'),
        ),
        migrations.AlterField(
            model_name='reportelab',
            name='r7cubo2',
            field=models.FloatField(blank=True, null=True, verbose_name='AH_R7Diacubo2'),
        ),
        migrations.AlterField(
            model_name='reportelab',
            name='r7cubo3',
            field=models.FloatField(blank=True, null=True, verbose_name='AI_R7Diacubo3'),
        ),
    ]
