# Generated by Django 2.1.15 on 2023-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0016_auto_20230410_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelab',
            name='_sio2',
            field=models.FloatField(blank=True, null=True, verbose_name='AT_%SiO2'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='densidad',
            field=models.FloatField(blank=True, null=True, verbose_name='AS_Densidad_p(g/cm3)'),
        ),
    ]
