# Generated by Django 2.1.15 on 2023-04-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0017_auto_20230411_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelab',
            name='_ai2o3',
            field=models.FloatField(blank=True, null=True, verbose_name='AU_%AI2O3'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='_fe2o3',
            field=models.FloatField(blank=True, null=True, verbose_name='AV_Fe2O3%'),
        ),
    ]
