# Generated by Django 2.1.15 on 2023-04-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0019_auto_20230411_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelab',
            name='c2s',
            field=models.FloatField(blank=True, null=True, verbose_name='BI_%C2S'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='c3a',
            field=models.FloatField(blank=True, null=True, verbose_name='BJ_%C3A'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='c3s',
            field=models.FloatField(blank=True, null=True, verbose_name='BH_%C3S'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='c4af',
            field=models.FloatField(blank=True, null=True, verbose_name='BK_%C4AF'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='callibre',
            field=models.FloatField(blank=True, null=True, verbose_name='BE_%Callibre'),
        ),
        migrations.AddField(
            model_name='reportelab',
            name='ri',
            field=models.FloatField(blank=True, null=True, verbose_name='BG_%RI'),
        ),
    ]
