# Generated by Django 2.1.15 on 2023-04-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0021_auto_20230411_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportelab',
            name='toneladasprod',
        ),
    ]
