# Generated by Django 2.1.15 on 2023-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0023_auto_20230412_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportelab',
            name='comentarios',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='CC_Comentarios'),
        ),
    ]
