# Generated by Django 4.1.7 on 2023-04-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0024_auto_20230412_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportelab",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
