# Generated by Django 5.0.1 on 2024-01-24 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='id_Producto')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='name_Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='boquillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_boquilla', models.IntegerField(blank=True, null=True, verbose_name='#_boquilla')),
                ('name_Producto', models.CharField(max_length=60, unique=True, verbose_name='name_Producto')),
                ('idbq', models.BigIntegerField(blank=True, null=True, verbose_name='idBQ')),
                ('sp', models.FloatField(blank=True, null=True, verbose_name='setpoint')),
                ('peso', models.FloatField(blank=True, null=True, verbose_name='peso_kg')),
                ('sp_ajuste1', models.FloatField(blank=True, null=True, verbose_name='sp_ajuste1')),
                ('sp_ff', models.FloatField(blank=True, null=True, verbose_name='sp_ajuste2')),
                ('dia', models.IntegerField(blank=True, null=True, verbose_name='dia')),
                ('hora', models.IntegerField(blank=True, null=True, verbose_name='dia')),
                ('min', models.IntegerField(blank=True, null=True, verbose_name='dia')),
                ('seg', models.IntegerField(blank=True, null=True, verbose_name='dia')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_producto', to='boquillas.productos')),
            ],
            options={
                'verbose_name': 'Boquilla',
                'verbose_name_plural': 'Boquillas',
            },
        ),
    ]
