# Generated by Django 5.0.1 on 2024-01-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boquillas', '0002_rename_name_producto_boquillas_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boquillas',
            old_name='producto',
            new_name='name_producto',
        ),
    ]
