# Generated by Django 5.0.1 on 2024-01-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boquillas', '0003_rename_producto_boquillas_name_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='boquillas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
