# Generated by Django 5.0.1 on 2024-01-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boquillas', '0004_boquillas_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boquillas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='feccha'),
        ),
        migrations.AlterField(
            model_name='boquillas',
            name='hora',
            field=models.IntegerField(blank=True, null=True, verbose_name='hora'),
        ),
        migrations.AlterField(
            model_name='boquillas',
            name='min',
            field=models.IntegerField(blank=True, null=True, verbose_name='min'),
        ),
        migrations.AlterField(
            model_name='boquillas',
            name='name_producto',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='name_Producto'),
        ),
        migrations.AlterField(
            model_name='boquillas',
            name='seg',
            field=models.IntegerField(blank=True, null=True, verbose_name='seg'),
        ),
    ]
