# Generated by Django 5.0.1 on 2024-01-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boquillas', '0005_alter_boquillas_created_at_alter_boquillas_hora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='id',
            new_name='id_Producto',
        ),
    ]
