# Generated by Django 5.0.1 on 2024-01-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boquillas', '0006_rename_id_productos_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_Producto',
            field=models.IntegerField(unique=True, verbose_name='id_Producto'),
        ),
    ]
