# Generated by Django 5.0.1 on 2024-01-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boquillas', '0007_productos_id_alter_productos_id_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='boquillas',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
    ]
