# Generated by Django 5.0.1 on 2024-01-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boquillas', '0008_delete_boquillas_delete_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Producto', models.IntegerField(unique=True, verbose_name='id_Producto')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='name_Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
