# Generated by Django 5.0.1 on 2024-01-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boquillas', '0010_boquillas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='boquillas',
        ),
    ]
