# Generated by Django 5.0.1 on 2024-01-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boquillas', '0012_boquillas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='boquillas',
        ),
    ]
