# Generated by Django 5.0.1 on 2024-01-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boquillas', '0014_boquillas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boquillas',
            name='created_at',
        ),
    ]
