# Generated by Django 5.0.1 on 2024-02-16 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boquillas', '0016_productos_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='mezclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.IntegerField(blank=True, null=True, verbose_name='batch_id')),
                ('lote', models.IntegerField(blank=True, null=True, verbose_name='lote')),
                ('name_producto', models.CharField(blank=True, max_length=60, null=True, verbose_name='name_Producto')),
                ('silo1', models.FloatField(blank=True, null=True, verbose_name='silo1')),
                ('silo2', models.FloatField(blank=True, null=True, verbose_name='silo2')),
                ('silo3', models.FloatField(blank=True, null=True, verbose_name='silo3')),
                ('silo4', models.FloatField(blank=True, null=True, verbose_name='silo4')),
                ('silo5', models.FloatField(blank=True, null=True, verbose_name='silo5')),
                ('silo6', models.FloatField(blank=True, null=True, verbose_name='silo6')),
                ('silo7', models.FloatField(blank=True, null=True, verbose_name='silo7')),
                ('silo8', models.FloatField(blank=True, null=True, verbose_name='silo8')),
                ('year_start', models.IntegerField(blank=True, null=True, verbose_name='year_start')),
                ('month_start', models.IntegerField(blank=True, null=True, verbose_name='month_start')),
                ('day_start', models.IntegerField(blank=True, null=True, verbose_name='day_start')),
                ('hour_start', models.IntegerField(blank=True, null=True, verbose_name='hour_start')),
                ('minute_start', models.IntegerField(blank=True, null=True, verbose_name='minute_start')),
                ('second_start', models.IntegerField(blank=True, null=True, verbose_name='second_start')),
                ('year_end', models.IntegerField(blank=True, null=True, verbose_name='year_end')),
                ('month_end', models.IntegerField(blank=True, null=True, verbose_name='month_end')),
                ('day_end', models.IntegerField(blank=True, null=True, verbose_name='day_end')),
                ('hour_end', models.IntegerField(blank=True, null=True, verbose_name='hour_end')),
                ('minute_end', models.IntegerField(blank=True, null=True, verbose_name='minute_end')),
                ('second_end', models.IntegerField(blank=True, null=True, verbose_name='second_end')),
                ('bz_agre1_sp', models.FloatField(blank=True, null=True, verbose_name='bz_agre1_sp')),
                ('bz_agre1_pv', models.FloatField(blank=True, null=True, verbose_name='bz_agre1_pv')),
                ('bz_agre2_sp', models.FloatField(blank=True, null=True, verbose_name='bz_agre2_sp')),
                ('bz_agre2_pv', models.FloatField(blank=True, null=True, verbose_name='bz_agre2_pv')),
                ('bz_agre3_sp', models.FloatField(blank=True, null=True, verbose_name='bz_agre3_sp')),
                ('bz_agre3_pv', models.FloatField(blank=True, null=True, verbose_name='bz_agre3_pv')),
                ('bz_agre4_sp', models.FloatField(blank=True, null=True, verbose_name='bz_agre4_sp')),
                ('bz_agre4_pv', models.FloatField(blank=True, null=True, verbose_name='bz_agre4_pv')),
                ('bz_cem1_sp', models.FloatField(blank=True, null=True, verbose_name='bz_cem1_sp')),
                ('bz_cem1_pv', models.FloatField(blank=True, null=True, verbose_name='bz_cem1_pv')),
                ('bz_cem2_sp', models.FloatField(blank=True, null=True, verbose_name='bz_cem2_sp')),
                ('bz_cem2_pv', models.FloatField(blank=True, null=True, verbose_name='bz_cem2_pv')),
                ('bz_adit_sp', models.FloatField(blank=True, null=True, verbose_name='bz_adit_sp')),
                ('bz_adit_pv', models.FloatField(blank=True, null=True, verbose_name='bz_adit_pv')),
                ('time_mezcla', models.FloatField(blank=True, null=True, verbose_name='time_mezcla')),
                ('datetime_plc', models.DateTimeField(blank=True, null=True, verbose_name='datatime_plc')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_producto2', to='boquillas.productos')),
            ],
        ),
    ]
