# Generated by Django 5.0.1 on 2024-02-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boquillas', '0017_mezclado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezclado',
            name='total_pv',
            field=models.FloatField(blank=True, null=True, verbose_name='total_pv'),
        ),
        migrations.AddField(
            model_name='mezclado',
            name='total_sp',
            field=models.FloatField(blank=True, null=True, verbose_name='total_sp'),
        ),
        migrations.AddField(
            model_name='mezclado',
            name='total_ton',
            field=models.FloatField(blank=True, null=True, verbose_name='total_ton'),
        ),
    ]
