# Generated by Django 4.0.1 on 2022-02-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jpg_imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='silos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silo', models.TextField(blank=True, db_column='silo', null=True)),
                ('material', models.TextField(blank=True, db_column='material', null=True)),
                ('codigo_sap', models.BigIntegerField(blank=True, db_column='codigo_sap', null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('toneladas', models.FloatField(blank=True, db_column='toneladas', null=True)),
                ('nivel', models.FloatField(blank=True, db_column='nivel', null=True)),
                ('metros', models.FloatField(blank=True, db_column='metros', null=True)),
                ('estado_silo', models.TextField(blank=True, db_column='estado_silo', null=True)),
                ('fecha_estado_silo', models.DateTimeField(blank=True, db_column='fecha_estado_silo', null=True)),
                ('estado_pedido', models.TextField(blank=True, db_column='estado_pedido', null=True)),
                ('fecha_estado_pedido', models.DateTimeField(blank=True, db_column='fecha_estado_pedido', null=True)),
                ('ultimo_llenado', models.DateTimeField(blank=True, db_column='ultimo_llenado', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='txt_inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='xlsx_repuestos1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='files1/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
