# Generated by Django 4.0.1 on 2022-05-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidos_id', models.BigIntegerField(db_column='pedido_id')),
                ('codigo_sap', models.BigIntegerField(db_column='codigo_sap')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('toneladas', models.FloatField(blank=True, db_column='toneladas', null=True)),
                ('nivel_porcen', models.FloatField(blank=True, db_column='nivel', null=True)),
                ('metros', models.FloatField(blank=True, db_column='metros', null=True)),
                ('estado_pedido', models.TextField(blank=True, db_column='estado_pedido', null=True)),
                ('fecha_pedido', models.DateTimeField(blank=True, db_column='fecha_estado_pedido', null=True)),
            ],
        ),
    ]
