# Generated by Django 4.0.1 on 2022-05-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='codigo_sap',
            field=models.BigIntegerField(blank=True, db_column='codigo_sap', null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pedidos_id',
            field=models.BigIntegerField(blank=True, db_column='pedido_id', null=True),
        ),
    ]
