# Generated by Django 4.0.1 on 2022-05-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_pedidos_codigo_sap_alter_pedidos_pedidos_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='metros',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fecha_cerrado',
            field=models.DateTimeField(blank=True, db_column='fecha_cerrado', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='nivel_metros',
            field=models.FloatField(blank=True, db_column='nivel_metros', null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado_pedido',
            field=models.IntegerField(blank=True, db_column='estado_pedido', null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_pedido',
            field=models.DateTimeField(blank=True, db_column='fecha_pedido', null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='nivel_porcen',
            field=models.FloatField(blank=True, db_column='nivel_porcen', null=True),
        ),
    ]
