# Generated by Django 4.0.1 on 2022-05-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_remove_pedidos_metros_pedidos_fecha_cerrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sap', models.IntegerField(blank=True, db_column='material', null=True)),
                ('nombre_material', models.TextField(blank=True, db_column='Nom_material', null=True)),
                ('nombre_corto', models.BigIntegerField(blank=True, db_column='Nom_corto', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(blank=True, db_column='Planta', null=True)),
                ('CodigoPlanta', models.BigIntegerField(blank=True, db_column='CodigoPlanta', null=True)),
            ],
        ),
    ]
