# Generated by Django 4.0.1 on 2022-06-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_silosml'),
    ]

    operations = [
        migrations.AddField(
            model_name='silos',
            name='altura_cilindro',
            field=models.FloatField(blank=True, db_column='altura_cilindro', null=True),
        ),
        migrations.AddField(
            model_name='silos',
            name='radio_cilindro',
            field=models.FloatField(blank=True, db_column='radio_cilindro', null=True),
        ),
        migrations.AddField(
            model_name='silosml',
            name='altura_cilindro',
            field=models.FloatField(blank=True, db_column='altura_cilindro', null=True),
        ),
        migrations.AddField(
            model_name='silosml',
            name='radio_cilindro',
            field=models.FloatField(blank=True, db_column='radio_cilindro', null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre_corto',
            field=models.CharField(blank=True, db_column='Nom_corto', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='silos',
            name='silo',
            field=models.CharField(blank=True, db_column='silo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='silosml',
            name='silo',
            field=models.CharField(blank=True, db_column='silo', max_length=20, null=True),
        ),
    ]
