# Generated by Django 4.0.1 on 2022-06-30 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_silos_altura_cilindro_silos_radio_cilindro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silos',
            name='description',
        ),
        migrations.RemoveField(
            model_name='silos',
            name='material',
        ),
        migrations.AlterField(
            model_name='silos',
            name='codigo_sap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='components.material'),
        ),
    ]
