# Generated by Django 4.0.1 on 2022-06-30 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_remove_silos_description_remove_silos_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silos',
            name='codigo_sap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='components.material'),
        ),
    ]
