# Generated by Django 4.0.1 on 2022-06-30 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_alter_silos_codigo_sap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silosml',
            name='description',
        ),
        migrations.RemoveField(
            model_name='silosml',
            name='material',
        ),
        migrations.AlterField(
            model_name='silosml',
            name='codigo_sap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productosML', to='components.material'),
        ),
    ]
