# Generated by Django 4.0.1 on 2022-06-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_remove_silosml_description_remove_silosml_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='densidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
