# Generated by Django 4.0.1 on 2022-08-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_material_densidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='ton_max',
            field=models.FloatField(blank=True, db_column='ton_max', null=True),
        ),
    ]
