# Generated by Django 3.2.5 on 2022-09-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_pedidos_ton_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoressensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.FloatField(blank=True, db_column='Nivel', null=True)),
                ('origen', models.TextField(blank=True, db_column='Origen', null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
                ('nombre_silo', models.TextField(blank=True, db_column='nombre_Silo', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'ValoresSensores',
                'managed': False,
            },
        ),
    ]
