# Generated by Django 3.2.5 on 2023-02-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_auto_20230227_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='nom_silo',
            field=models.TextField(blank=True, db_column='nombre_silo', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='planta',
            field=models.TextField(blank=True, db_column='planta', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='prioridad',
            field=models.IntegerField(blank=True, db_column='prioridad', null=True),
        ),
    ]
