# Generated by Django 3.2.5 on 2023-02-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_auto_20230227_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jpg_imagenes',
        ),
        migrations.DeleteModel(
            name='txt_inventario',
        ),
        migrations.DeleteModel(
            name='xlsx_repuestos1',
        ),
    ]
