# Generated by Django 4.1.7 on 2023-03-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0016_auto_20230227_2155"),
    ]

    operations = [
        migrations.AddField(
            model_name="llegadas",
            name="nom_silo",
            field=models.TextField(blank=True, db_column="nombre_silo", null=True),
        ),
        migrations.AddField(
            model_name="llegadas",
            name="planta",
            field=models.TextField(blank=True, db_column="planta", null=True),
        ),
    ]
