# Generated by Django 4.1.7 on 2023-03-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0017_llegadas_nom_silo_llegadas_planta"),
    ]

    operations = [
        migrations.AddField(
            model_name="silos",
            name="setpoint",
            field=models.FloatField(blank=True, db_column="setpoint", null=True),
        ),
    ]
