# Generated by Django 4.1.7 on 2023-03-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0018_silos_setpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="silos",
            name="planta",
            field=models.CharField(
                blank=True, db_column="planta", max_length=80, null=True
            ),
        ),
        migrations.AddField(
            model_name="silosml",
            name="planta",
            field=models.CharField(
                blank=True, db_column="planta", max_length=80, null=True
            ),
        ),
    ]
