# Generated by Django 4.1.7 on 2023-03-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0019_silos_planta_silosml_planta"),
    ]

    operations = [
        migrations.AddField(
            model_name="silos",
            name="metrosxbotella",
            field=models.FloatField(blank=True, db_column="metrosxbotella", null=True),
        ),
    ]
