# Generated by Django 5.0.1 on 2024-09-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedidorAguaLanzasMolino3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_column='datatime_db')),
                ('volumen', models.PositiveIntegerField(db_column='volumen_totalizado', default=0)),
            ],
            options={
                'verbose_name': 'MedidorDeAguaLanzasMolino3',
                'verbose_name_plural': 'MedidasDeAguaLanzasMolino3',
            },
        ),
        migrations.CreateModel(
            name='MedidorAguaRio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_column='datatime_db')),
                ('datatime', models.DateTimeField(blank=True, db_column='datatime_plc', null=True)),
                ('volumen', models.PositiveIntegerField(db_column='volumen_totalizado', default=0)),
                ('flujo', models.FloatField(db_column='medida_flujo', default=0)),
                ('nivel', models.FloatField(db_column='nivel_tanq', default=0)),
                ('bomba1', models.PositiveIntegerField(db_column='estado_bomba1', default=0)),
                ('bomba2', models.PositiveIntegerField(db_column='estado_bomba2', default=0)),
            ],
            options={
                'verbose_name': 'MedidorDeAguaRio',
                'verbose_name_plural': 'MedidasDeAguaDeRio',
            },
        ),
    ]
